spring:
  application:
    name: ezybuy-ecommerce
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/ezybuy-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

# app:
#   secret:
#     key: YFiWZGqMKgeadnQGmwGtDMXpFHxbHVXrZEFwxhacjyzmzxpYipAdfwqePYnuKmKdTJer
#   jwt:
#     expiration: 3600000
